# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: batch.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61tch.proto\"\xa2\x01\n\x07Request\x12\x0e\n\x06rfw_id\x18\x08 \x01(\x05\x12\x12\n\nbench_type\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x03 \x01(\x05\x12\x12\n\nbatch_unit\x18\x04 \x01(\x05\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\x12\x11\n\tdata_type\x18\x06 \x01(\t\x12\x16\n\x0e\x64\x61ta_analytics\x18\x07 \x01(\t\"\x9a\x01\n\x08Response\x12\x0e\n\x06rfw_id\x18\x01 \x01(\x05\x12\x15\n\rlast_batch_id\x18\x02 \x01(\x05\x12*\n\nbatch_data\x18\x03 \x03(\x0b\x32\x16.Response.DATA_SAMPLES\x12\x16\n\x0e\x64\x61ta_analytics\x18\x04 \x01(\x02\x1a#\n\x0c\x44\x41TA_SAMPLES\x12\x13\n\x0bsample_data\x18\x01 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'batch_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=16
  _REQUEST._serialized_end=178
  _RESPONSE._serialized_start=181
  _RESPONSE._serialized_end=335
  _RESPONSE_DATA_SAMPLES._serialized_start=300
  _RESPONSE_DATA_SAMPLES._serialized_end=335
# @@protoc_insertion_point(module_scope)
